### ISSUE TITLE
[?] How to include external packages in preview

### ISSUE THREAD

**Issue by ryrych** [chromaui/intro-storybook-vue-template#1]
@jonniebigodes first, thanks for preparing this template. Having the basic setup I'm trying to make external library (https://vuematerial.io/) work with Storybook.

Material components work in the regular Vue application.

```js
import Vue from "vue";
import App from "./App.vue";

import { MdButton, MdContent, MdTabs } from 'vue-material/dist/components'
import 'vue-material/dist/vue-material.min.css'
import 'vue-material/dist/theme/default.css'

Vue.use(MdButton)
Vue.use(MdContent)
Vue.use(MdTabs)

Vue.config.productionTip = false;

new Vue({
  render: h => h(App)
}).$mount("#app");
```

`md-button` when used in `Button.vue` is not recognized in the Storybook context, even when it `MdButton` is referenced in `components`.
I've followed many articles about setting up Storybook and Vue. Different setups cover Storybook config in the following files: main.js, preview.js, config.js, webpack config. Storybook vue documentation is not clear in this regard.

What and where should I initialize external library like vue-material so that it is recognized by Storybook?

**Comment by jonniebigodes** [comment]
@ryrych no need to thank, glad that it helped you get started real quick. Based on your question, it seems that falls a bit out of the scope of this template. As it's meant to get you and other readers onboarded into the Intro to Storybook tutorial with the least amount of effort. Run a couple of commands and presto. To be honest with you, i haven't checked the library you've mentioned. But something worth investigating. Let me take a look into it and see if i can come up with a sample repo for you. Do you mind waiting a bit while this is looked into?

Stay safe

**Comment by jonniebigodes** [comment]
@ryrych we've updated the [official documentation](https://storybook.js.org/docs/vue/writing-stories/decorators) recently and to include an example on how to set up external packages globally in Storybook's `preview.js` file. 

Let me know if it helped with your case. For now and I hope you don't mind. I'm closing this issue and I'm more than glad to re-open it should it be the case.

Have a great week.

Stay safe
